### ISSUE TITLE
support for egeo.unisi.it (ERDAS ecw server Zoomed maps)

### ISSUE THREAD

**Issue by Cartographic** [lovasoa/dezoomify#207]
I ask kindly to take care of my request
http://www.egeo.unisi.it/
it's a website full of Italian geological related maps

For the reason written above: several of rare or unique geological maps (all world)

Example URLs
http://www.egeo.unisi.it/index.php/dettaglio-carta/?act=see&id=2491

Current error message
Error
Uncaught Error: Unable to find a proper dezoomer for:
http://www.egeo.unisi.it/index.php/dettaglio-carta/?act=see&id=2491

(https://ophir.alwaysdata.net/dezoomify/dezoomers/automatic.js:30)

Hi dears,
I tried dezoomify but it won't work on [this site](http://www.egeo.unisi.it/index.php/dettaglio-carta/?act=see&id=2491)
I hope somebody can explain me why and help

Given error

 is the following

>  Error
Uncaught Error: Invalid seadragon XML info file: http://www.egeo.unisi.it/wp-includes/wlwmanifest.xml
(http://ophir.alwaysdata.net/dezoomify/zoommanager.js:178)
You should read our FAQ, and, if you think this is an issue with dezoomify itself, report a bug on the bugtracker .

![2018-03-02_08-40-31-029](https://user-images.githubusercontent.com/36972587/36888416-a805762a-1df5-11e8-9244-348912d6a9b7.png)

**Comment by Cartographic** [comment]
I founf this document that explains about the zoomifier used https://gis.stackexchange.com/questions/239145/how-to-download-whole-ecw-or-jpg-tiles-from-web-viewer
"it's probably using an ERDAS ecw server "
In fact inspecting the page I found the tile is
"http://www.neogeo.unisi.it/ecwp/ImageX.dll?image?cache=true&transparent=true&type=jpg&l=0&tx=39&ty=27&ts=256&fill=FFFFFF&quality=60&layers=/egeo/NULL/null092.ecw&srs=EPSG:RAW"

**Comment by Cartographic** [comment]
Other info

ERDAS IMAGINE software uses a tiled format to store raster layers. The tiled format allows raster layers to be displayed and resampled quickly. The default tile size used to be 64 pixels by 64 pixels, but now appears to be 512 pixels by 512 pixels. Within a tile, raster data uses the BSQ_enc ordering for pixels. Optionally, a large raster layer may be organized in a "pyramid" for faster processing. In pyramid layers, reduced, subsampled raster layers are created from the original raster layer.

**Comment by Cartographic** [comment]
Ho dear, how to get involved in the process ?

**Comment by Cartographic** [comment]
Thank for considering my request ...

**Comment by Cartographic** [comment]
I ask you for support my doubt and fix the dezoomifier

**Comment by Cartographic** [comment]
file to download here http://www.egeo.unisi.it/index.php/dettaglio-carta/?act=see&id=2491

**Comment by lovasoa** [comment]
Please avoid editing the issue title repetitively. dezoomify is not a commercial product. I work on it for fun, on my free time. 
Every time you update the issue, I receive a notification. Asking for updates every few months is ok, spamming the issue is not. This is just making this project less fun to work on, and thus less likely to receive updates.

That said, I am going to have a look at your website.

**Comment by lovasoa** [comment]
OK, I had a look at it. There is not bug in dezoomify, this is simply a format that is not supported.
However, the generic dezoomer seems to be working well with it:

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://www.neogeo.unisi.it/ecwp/ImageX.dll?image?l=0&tx={{X}}&ty={{Y}}&ts=2000&quality=100&layers=/egeo/NULL/null092.ecw

![carta_geo](https://user-images.githubusercontent.com/552629/71623743-046a5400-2bdf-11ea-9ad2-6c2f9c5f8b86.jpg)


Please read [our FAQ](https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ) for more information about how to use the generic dezoomer.

**Comment by lovasoa** [comment]
Alternatively, you can also use [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs) and its *custom yaml* dezoomer, with the following `tiles.yaml` :

```yaml
# The url of individual tiles, where {{ expressions }} will be evaluated using the variables below
url_template: "http://www.neogeo.unisi.it/ecwp/ImageX.dll?image?l=0&tx={{x/tile_size}}&ty={{y/tile_size}}&ts={{tile_size}}&quality=100&layers=/egeo/NULL/null092.ecw"

variables:
  # The x position of tiles goes from 0 to the image width with an increment of the tile width
  - name: x
    from: 0
    to: 11840 # Image width
    step: 2000 # Tile width

  - name: y
    from: 0
    to: 8976 # Image height
    step: 2000 # Tile height

  - name: tile_size
    value: 2000
```

The image width and height can be found in your browser's network inspector, in the case of this image: http://www.neogeo.unisi.it/ecwp/ImageX.dll?dsinfo?layers=/egeo/NULL/null092.ecw
