### ISSUE TITLE
[new site support] : davidrumsey

### ISSUE THREAD

**Issue by xmahd** [lovasoa/dezoomify#339]
davidrumsey collection
https://www.davidrumsey.com

### Example URLs

https://www.davidrumsey.com/luna/servlet/workspace/handleMediaPlayer?lunaMediaId=RUMSEY~8~1~318335~90087263

### Notice

some of the pictures can be download on original page by different format ( like img2000 or sth ) or view it with zooming 

some of picture you can just view it with zoomable system

**Comment by lovasoa** [comment]
I don't think you need dezoomify for this site.

While browsing the zoomed image, open your browser's network monitor, and look at the URL of the image tiles that are being loaded.

Example: `https://media.davidrumsey.com/MediaManager/srvr?mediafile=/JP2K/RUMSEY~8~1/179/13243029.jp2&x=6000&y=0&width=184&height=525&level=3` 

As you see, there are parameters (x, y, width, and height) that allow you to select the region of the image you want. You can just open the page source to find the width and height of the image, and use them in the image parameters:

`https://media.davidrumsey.com/MediaManager/srvr?mediafile=/JP2K/RUMSEY~8~1/179/13243029.jp2&x=0&y=0&width=7476&height=4202&level=0`

![img](https://user-images.githubusercontent.com/552629/67905203-e6498e80-fb70-11e9-978e-dbec49002831.jpg)

**Comment by xmahd** [comment]
How can I turned all tiles to one pic ? 
Like to picture that you created for example

**Comment by lovasoa** [comment]
But this is a lot of work, given that the site already allows you to download the full-size image in jpeg2000. You can just download the file in jpeg2000 and then convert it to whatever pleases you.

**Comment by xmahd** [comment]
Thanks
You Right , Most of data allows to download ,
but some of them you can Just view it with Zooming system .

Your way works great , thxx

**Comment by bboyn12** [comment]
thanks good job,can help in this map https://www.davidrumsey.com/luna/servlet/workspace/handleMediaPlayer?lunaMediaId=RUMSEY~8~1~303661~90074314 or this https://www.davidrumsey.com/luna/servlet/workspace/handleMediaPlayer?lunaMediaId=RUMSEY~8~1~303642~90074311 please

**Comment by lovasoa** [comment]
@bboyn12 : did you try the procedure described above ? Did you watch [the tutorial](https://www.youtube.com/watch?v=UhX-2zanOo8&feature=youtu.be) ? Where are you stuck ?

**Comment by bboyn12** [comment]
yes,I'm try but I have this HTTP Status 404 - Requested media not found.

**Comment by lovasoa** [comment]
You will have to be more specific if you want to get help. Can you give precise details of all the steps you are following, and at each step, the result you are seeing ? You can include screenshots.

**Comment by bboyn12** [comment]
![image](https://user-images.githubusercontent.com/58958596/70993260-89277f00-20c3-11ea-941b-2b4269aae6d2.png)

**Comment by bboyn12** [comment]
I'm followed the video and it been successful with map,but don't successful  with others

**Comment by lovasoa** [comment]
Ok, I see. It looks like the server does not support serving huge images at once. These maps are really huge. 

I think you have two solutions:

## "Easy" solution
The easy solution is to download the image at a lower zoom level, such as zoom level 1 or 2. Of course the resulting image will be smaller, but this allows you to download the image directly from the server without any tool.

### How to download the image at a smaller zoom level
To download at a certain level `n`, replace `level=0` by `level=n`, and divide the width and height by 2ⁿ. 
For instance, to download at level 2 an image of width 8000 and height 1000: replace `level=0` by `level=2`, and replace `width=8000` by `width=2000` (8000/2^2 = 2000) and replace `height=1000` with `height=250` (1000/2^2=250).

In your case, this gives the following URL:

`https://media.davidrumsey.com/MediaManager/srvr?mediafile=/JP2K/RUMSEY~8~1/179/10130083.jp2&x=0&y=0&width=12625&height=13079&level=2`

![canvas](https://user-images.githubusercontent.com/552629/70996215-9bf58000-20d2-11ea-8dd0-690789a371f2.jpg)


## Full quality solution

You can also use [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs) and its *custom YAML* dezoomer to download the image tile by tile.
Follow the instructions on dezoomify-rs project page for help with its use. If the instructions are unclear or the software doesn't work as expected, you can [open an issue](https://github.com/lovasoa/dezoomify-rs/issues) there.

Here is an example `tiles.yaml` file that you could use for the image in your first example:

```yaml
# The url of individual tiles, where {{ expressions }} will be evaluated using the variables below
url_template: "https://media.davidrumsey.com/MediaManager/srvr?mediafile=/JP2K/RUMSEY~8~1/179/10130083.jp2&x={{x}}&y={{y}}&width=512&height=512&level=0"

variables:
  # The x position of tiles goes from 0 to the image width with an increment of the tile width
  - name: x
    from: 0
    to: 51300 # Image width
    step: 512 # Tile width

  - name: y
    from: 0
    to: 52317 # Image height
    step: 512 # Tile height
```
