### ISSUE TITLE
Downloading from Besançon Museum

### ISSUE THREAD

**Issue by Sindi43** [lovasoa/dezoomify#345]
Hello,

I tried to download images from this site:

http://memoirevive.besancon.fr/ark:/48565/a011485786957vRn4Wc/1/1

Unfortunately dezoomify doesn't work...

Can you help me?

Thx!

**Comment by lovasoa** [comment]
They seem to be using an obscure non-standard image viewer called [mnesys](https://naoned.fr/logiciels/mnesys-archives/), maintained by a french company called [naoned](https://naoned.fr).

The format is not supported by dezoomify, but you can use [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs) on it.

You'll need to find the image dimensions and the tile URL pattern (you can find both by opening your browser's [network inspector](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor)) while browsing the image.

In your example, the dimensions are in 

http://memoirevive.besancon.fr/accounts/mnesys_besancon/datas/medias/Musees/M0332/D-991-1-2_jpg_/p.xml

and the tile URL format is

```
http://memoirevive.besancon.fr/accounts/mnesys_besancon/datas/medias/Musees/M0332/D-991-1-2_jpg_/3_{n}.jpg
```


Using these information, one can create the following `tiles.yaml` file for [dezoomify-rs's custom yaml dezoomer](https://github.com/lovasoa/dezoomify-rs#custom-yaml)

```yaml
# The url of individual tiles, where {{ expressions }} will be evaluated using the variables below
url_template: "http://memoirevive.besancon.fr/accounts/mnesys_besancon/datas/medias/Musees/M0332/D-991-1-2_jpg_/3_{{
  x/tile_size +
  y/tile_size * (1+width/tile_size)
}}.jpg"

variables:
  # The x position of tiles goes from 0 to the image width with an increment of the tile width
  - name: x
    from: 0
    to: 4904 # Image width
    step: 512 # Tile width

  - name: y
    from: 0
    to: 3928 # Image height
    step: 512 # Tile height

  - name: tile_size
    value: 512

  - name: width
    value: 4904 # Image width
```

![dezoomified](https://user-images.githubusercontent.com/552629/70163960-9fdfd600-16c0-11ea-9fdd-858b42692609.jpg)
