### ISSUE TITLE
Downloading from Besançon Museum (2)

### ISSUE THREAD

**Issue by portraitsofrulers** [lovasoa/dezoomify#360]
Hello,

I tried to download image from this site: http://memoirevive.besancon.fr/ark:/48565/a011514878120Och07o/1/1

I used your instruction in this theme: https://github.com/lovasoa/dezoomify/issues/345
But unfortunately this way doesn't work, because in formatted URL you mentioned  3_{n}.jpg that not responds my image, where 2_{n}.jpg and 3_{n}.jpg both figured in network scanner. If I used only 3_{n},jpg in tiles.yaml it gets "moved out" image.

Can you help me?

Thanks!

**Comment by lovasoa** [comment]
Hello, 
  The procedure described in #345 works well with this image too. Be sure to update the image width in **both** positions where it appears inside the file.

```yaml
# The url of individual tiles, where {{ expressions }} will be evaluated using the variables below
url_template: "http://memoirevive.besancon.fr/accounts/mnesys_besancon/datas/medias/Musees/M0333/1694-1-3_01_jpg_/3_{{
  x/tile_size +
  y/tile_size * (1+width/tile_size)
}}.jpg"

variables:
  # The x position of tiles goes from 0 to the image width with an increment of the tile width
  - name: x
    from: 0
    to: 3732 # Image width
    step: 512 # Tile width

  - name: y
    from: 0
    to: 4397 # Image height
    step: 512 # Tile height

  - name: tile_size
    value: 512

  - name: width
    value: 3732 # Image width
```

![dezoomified](https://user-images.githubusercontent.com/552629/75983720-54201100-5ee9-11ea-888f-a01e2559ffcc.jpg)
