### ISSUE TITLE
[new site support] Downloading from Accademia Carrara

### ISSUE THREAD

**Issue by Sindi43** [lovasoa/dezoomify#414]
Hello,

I tried to download images from this site:

https://www.lacarrara.it/en/catalogo/81lc00140/?highlight=bellini

Unfortunately dezoomify doesn't work...

Can you help me?

Thx!

**Comment by lovasoa** [comment]
![maria](https://user-images.githubusercontent.com/552629/86510942-b421b800-bdf4-11ea-8f1b-1fd907571391.jpg)

**Comment by lovasoa** [comment]
You can use [dezoomify-rs](https://lovasoa.github.io/dezoomify-rs/) with the following tiles.yaml : 

```yaml
# The url of individual tiles, where {{ expressions }} will be evaluated using the variables below
url_template: "https://www.lacarrara.it/catalogo-content/81LC00140/5/{{x/256}}/{{30-y/256}}.jpg"

variables:
  # The x position of tiles goes from 0 to the image width with an increment of the tile width
  - name: x
    from: 0
    to: 5376 # Image width = 21 * 256
    step: 256 # Tile width

  - name: y
    from: 0
    to: 7680 # Image height
    step: 256 # Tile height

```
