### ISSUE TITLE
New site   https://horyuji-kondohekiga.jp/index.html

### ISSUE THREAD

**Issue by Kite2020** [lovasoa/dezoomify#461]
Hello!

I have tried to use dezoomify, Here is the link that I want to donw

https://horyuji-kondohekiga.jp/index.html

Please click on "Digital Viewer" ----"start"----"Mural No.1"

thank you somuch

**Comment by lovasoa** [comment]
You can find the color images in your browser's devtools : 

https://view.horyuji-kondohekiga.jp/asset/01_square.jpg
https://view.horyuji-kondohekiga.jp/asset/02_square.jpg
...
https://view.horyuji-kondohekiga.jp/asset/12_square.jpg 

![](https://view.horyuji-kondohekiga.jp/asset/01_square.jpg)

They are all served as squares, you'll have to resize them.

**Comment by Kite2020** [comment]
Thank you！

but click on "Digital Viewer" ----"start"----"Mural No.1"  we can see this pictures

then click button “**view glass photographic plates**” jump to  highresolution

I need the big one，I did not make it clear， sorry.

**Comment by lovasoa** [comment]
Their tiling system is quite unusual.

You can find the metadata here: https://view.horyuji-kondohekiga.jp/js/tileData.json

Each image has a *center* defined by a latitude and a longitude: ` "center": { "x": 135.339000, "z": 34.983517 }`

This center is then converted to an x,y position using a [mercator projection](https://en.wikipedia.org/wiki/Mercator_projection) and serves as a basis to compute the x,y coordinates of each tile.

The tiles are then loaded using the the information in tilesData.json : 

```
https://view.horyuji-kondohekiga.jp/tile/wall09/{{level}}/{{mercator x}}/{{mercator y}}.jpg
```

The `tilesData.json` mentioned above contains a showRange property that seems to indicate the start and end points of the mercator coordinates of the image `      "showRange": {
        "zoom": 16,
        "left": 57344,
        "right": 57500,
        "top": 25856,
        "bottom": 26041
      },`.

Using this information, you should be able to use [dezoomify-rs](https://lovasoa.github.io/dezoomify-rs/) and its [custom yaml](https://github.com/lovasoa/dezoomify-rs/wiki/Usage-example-for-the-custom-YAML-dezoomer) dezoomer to download the image.

Good luck, and please post your results here !

**Comment by lovasoa** [comment]
Here is a `tiles.yaml` for the first image : 

```yaml
# The url of individual tiles, where {{ expressions }} will be evaluated using the variables below
url_template: "https://view.horyuji-kondohekiga.jp/tile/wall01/16/{{
  x/256 + 57344
}}/{{
  y/256 + 25856
}}.jpg"

variables:
  # The x position of tiles goes from 0 to the image width with an increment of the tile width
  - name: x
    from: 0
    to: 39936 # Image width = (right-left)*tile_size
    step: 256 # Tile width

  - name: y
    from: 0
    to: 47360 # Image height
    step: 256 # Tile height

headers:
  Referer: https://view.horyuji-kondohekiga.jp/
```

Since the resulting image is huge, I advise you to use the experimental [IIIF output format](https://lovasoa.github.io/dezoomify-rs/#supported-output-image-formats)
