### ISSUE TITLE
[new site support]

### ISSUE THREAD

**Issue by gck982** [lovasoa/dezoomify#526]
### Site name and desciption
What is the name and the URL of the site you would like dezoomify to support ?
NYC Municipal Archives
http://nycma.lunaimaging.com/

Why is this site of particular interest ? The more popular the site, the more chance you have to see dezoomify supporting it someday.
It has thousands of high res digitized content of NYC History that is extremely helpful to researchers.

### Example URLs
 - Give the URLs of viewing pages
 - give the URLs of metadata files if you found them
 I am trying to pull this photo in high res:
http://nycma.lunaimaging.com/luna/servlet/detail/RECORDSPHOTOUNITARC~13~13~1550523~154033:bps_11931

### Current error message
Describe the error dezoomify currently gives you when you try to dezoomify images from this site.
Unable to fetch

**Comment by lovasoa** [comment]
Hello !

This is the same system as on davidrumsay. See: https://github.com/lovasoa/dezoomify/issues/339

Here is a tile URL

http://nycma.lunaimaging.com/MediaManager/srvr?mediafile=/JP2K/RECORDSPHOTOUNITARC-13-NA/1253/bps_11931.jp2&x=1500&y=3000&width=750&height=750&level=1

You can doownload it with https://dezoomify-rs.ophir.dev/

#### tiles.yaml

```yaml
# The url of individual tiles, where {{ expressions }} will be evaluated using the variables below
url_template: "http://nycma.lunaimaging.com/MediaManager/srvr?mediafile=/JP2K/RECORDSPHOTOUNITARC-13-NA/1253/bps_11931.jp2&x={{x}}&y={{y}}&width=512&height=512&level=0"

variables:
  # The x position of tiles goes from 0 to the image width with an increment of the tile width
  - name: x
    from: 0
    to: 6000 # Image width, search for "maxWidth" in the viewer page source
    step: 512 # Tile width

  - name: y
    from: 0
    to: 4800 # Image height
    step: 512 # Tile height
```

![img](https://user-images.githubusercontent.com/552629/108195380-f85d9080-7117-11eb-8d01-c5a10ea8f23b.jpg)
